  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mysql2:3308/db_xxx?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: user1234
